# 04 — Vectorized Calculations

**Goal:** To apply one calculation to an entire array without writing a loop.

In [1]:
import numpy as np

acc_x = np.array([0.10, 0.20, 0.30, 0.40])
print(acc_x)

[0.1 0.2 0.3 0.4]


In [2]:
# Add a constant to every value.
# This happens element by element.
adjusted = acc_x + 0.05
print(adjusted)

[0.15 0.25 0.35 0.45]


In [3]:
# Multiply every value by 2.
doubled = acc_x * 2
print(doubled)

[0.2 0.4 0.6 0.8]


In [4]:
# Square every value.
# Squaring is useful when calculating magnitude later.
squared = acc_x ** 2
print(squared)

[0.01 0.04 0.09 0.16]


## Summary

Vectorization means: **one operation applies to the whole array**.

This keeps code short and readable.